### ISSUE TITLE
Make the file I/O system

### ISSUE THREAD

**Issue by Lord-Scrubington-II** [cse110-fall21-group9/Digital-Cookbook-App#14]
Write a ES6 `class` that handles the file i/o operations that our app will need neatly.

Use the Node.js `fs` and `path` modules to accomplish the basic CRUD-related i/o ops first.

**Comment by haxoc** [comment]
Just merged #15 pr

**Comment by Lord-Scrubington-II** [comment]
Retroactive note: I finished writing up the file i/o system such that the basic CRUD ops can be supported. With this new architecture that has been provided by Electron, we now have a full-blown local backend to work with - `main.js` inside the Electron window. See issue #18 for more info.

**Comment by Lord-Scrubington-II** [comment]
Awaiting completion of core unit tests on CRUD operations.

**Comment by Lord-Scrubington-II** [comment]
The IOSystem has been completed for basic CRUD. The next step is other operations.
