### ISSUE TITLE
Core Features Implementation

### ISSUE THREAD

**Issue by StefanieDao** [cse110-fall21-group9/Digital-Cookbook-App#28]
### 1. ADD
Manual Add: 
>  - [x]  Design UI page for user to manually compose recipe

API Add (use Spoonacular to parse recipe from web) : 
> - [ ]   Add UI for user to parse recipe from a link

General:
>  - [x]  Build a JSON object from input
>  - [x]  Display new recipe card 
>  - [x] Send a message to backend to save JSON file at a directory (Done by backend team)
>  - [x]  Figure out how to inject the cached JSONobject into a web component (also, mapping recipe card the correct JSON file)

### 2. VIEW RECIPE 
>  - [x]  Show View Recipe Page when user clicks into a recipe card
>  - [ ]  Improve UI View Recipe Page (Seperate View for Ingredient/Instruction, Timer)

### 3. EDIT 
>  - [x] Show Edit Recipe Page when users click Edit for a recipe card
 (could be same as ADD page but with the information already populated for each field)
>  - [x] Modify information for the corresponding JSON file 
>  - [x] Modification is reflected on the recipe card on homepage when user hit Save

### 4. DELETE 
>  - [x]  Remove recipe card from homepage when user hit DELETE
> - [x] Remove the matching JSON file

### 5. SEARCH & SORT
>  - [x]  Basic Search: Use string matching and filter out results as user type
>  - [ ]  Advance Search: Search based on Tags, Ingredients

**Comment by Lord-Scrubington-II** [comment]
In terms of CRUD:

## Create
This is working, but unpolished.

## Read
All of the bones are there! I've already sent over a dictionary containing all the JSON data to the front end. One of our front end engineers needs to use it to instantiate all of the starting recipe cards.

## Update
Working in minimum form.

## Delete
Not working yet, but again, the bones are there. Define your own message for this and send it from front end when user presses delete button.

**Comment by haxoc** [comment]
Merged PR
