### ISSUE TITLE
Give the recipe cards a container with a scroll bar so that they can be scrolled through independently of the navbar

### ISSUE THREAD

**Issue by Lord-Scrubington-II** [cse110-fall21-group9/Digital-Cookbook-App#58]
As above. I think there actually might be a ***really convenient*** CSS attribute for this, but I don't remember the details.

**Comment by sidanand67** [comment]
Hello @Lord-Scrubington-II, 
Is this issue still available to fix?

**Comment by Lord-Scrubington-II** [comment]
> Hello @Lord-Scrubington-II, Is this issue still available to fix?

Sorry, this is an academic project and we are not allowed to enlist outside help. Hence, we are going to refuse. Appreciate the (implied) offer though.

**Comment by sidanand67** [comment]
Ok cool. No issues and Good Luck.

**Comment by StefanieDao** [comment]
Done!
