### ISSUE TITLE
Implement Recipe Search and then Recipe Sort

### ISSUE THREAD

**Issue by Lord-Scrubington-II** [cse110-fall21-group9/Digital-Cookbook-App#59]
Start with search by name and sort by date changed/name. Strengthen the date format that is stored in the JSON so that it contains the date AND time, OR one option is saving the time in milliseconds from the [Unix epoch](https://en.wikipedia.org/wiki/Unix_time).

**Comment by StefanieDao** [comment]
**Sreach**:
> - [x] By recipe's name
> - [ ] By recipe's tag
> - [ ] By ingredients

**Sort** 
> - [ ] By recipe's name (A-Z and Z-A)
> - [ ] By date added (Time Added: Newest to Older vs Oldest to Newest)

**Comment by haxoc** [comment]
Search works, no sorting.
