### ISSUE TITLE
Bugs to resolve 

### ISSUE THREAD

**Issue by StefanieDao** [cse110-fall21-group9/Digital-Cookbook-App#81]
- [x] Discard button does not work sometimes
- [ ] Recipe order mix up after edit
- [x] Add image to a recipe card with no image (it kinda duplicate the cards and the image does not load; this can be resolved by just press "Home" and upload the image again)

**Comment by Lord-Scrubington-II** [comment]
The image bug I think I fixed. was an issue with the conditions related to if the card had been opened before or not.

**Comment by StefanieDao** [comment]
Finished
